travis:
  secure:
    BINSTAR_TOKEN: prFF1HuN05PdoCQ2M6XOy3E1h0PVAny3rc1jXCw4mPR55xmaNcvCJM9+6CoWtL5H0EMP2zoScZSD66vY24cblCg9yBZZY33fkpSe/poQJjGc6huPK+NaUdr6B2nbpMrIY5dafPa1eYhP1VkCW7KVfylh8qdr9excY8LhKGWHXhjiVPabk5SoW67CU9+YwGSiZqFQDJqPKCtwqUwh6CVtl1PC3fct43wui6TcJJsV7GY5OPLEB2iXQHMxPAolyyKiA9cT5DwNawLQqboBtwvJGvctwMD0aowpNqkF5mRUW7UpF2FxQxctb9am+NPnQ4zbo83E4uC48ziR0LFnPteocFw1oOgOZts+UUIf6ZfW0luAOF6PMf9RugZeTXP0BgmDNv2m0UfpIYpY/iB9D8BZMoKdAWUQlQ2dOscsEP/xKgQ11DdUb7ra0i9X5K16Wj7w21zHXCQYI/hB2xSqdR3ZeYE0ZoTo/0jv0pm7/NyzsunVr4kJi1Mb87NzuvVju2qi3UZmGfeSNaBNuPpKc5XPIJ9SVoaFE6zQ96ZWHnjY1kEM2Bgl+JnR4TDzju34Ndgcy/PywAOCic0dFvjEp/Tjzq6WagGJMk/CWK1rAyuk/58TNjnAazk8XlSpeBRW5xsWt7RogBahyHrJS7NI33+xdb4JZDAjmn1wUFyL4CneJYs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
